### ISSUE TITLE
Usage of deprecated std::num::FromPrimitive

### ISSUE THREAD

**Issue by HolgerPeters** [brson/rust-sdl#165]
Trying to get rust-sdl working, I found that events.rs uses std::num::FromPrimitive which has been removed from rust by now (see https://github.com/rust-lang/rust/issues/16920 for more information). Thus, rust-sdl will not compile with newest rust.

~/.cargo/git/checkouts/rust-sdl-917d0a231cab7c3c/master/src/sdl/event.rs:4:5: 4:28 error: unresolved import `std::num::FromPrimitive`. There is no `FromPrimitive` in `std::num`

**Comment by lstat** [comment]
Thanks!
