### ISSUE TITLE
Upload 0.3.6 to cargo.io

### ISSUE THREAD

**Issue by mikezaby** [brson/rust-sdl#166]
The version `0.3.5` that is uploaded to crates.io is not the latest and it's not compiling with rust version `1.0.0`, please upload the latest version. 
Also it would be nice if there are the `tags` and `releases` for the new versions

**Comment by lgrz** [comment]
Hey there, I'm one of the maintainers, I'll see about getting a new version published sometime soon.

@brson Would you like to publish a new version? I can if you'd prefer, I would need publish access on crates.io (if you're happy to do that of course). Thanks.

**Comment by brson** [comment]
@lstat I'm not sure if I even know how! But I will try right now.

**Comment by brson** [comment]
I published master as 0.3.6 and tagged it.

**Comment by brson** [comment]
@lstat I also made you an owner of `sdl` on crates.io.

**Comment by lgrz** [comment]
@brson Great, thanks for that!
